### ISSUE TITLE
Undeclared dependency on Joda time

### ISSUE THREAD

**Issue by cdman** [nielsbasjes/logparser#25]
It seems that httpdlog-parser version 2.3 has an undeclared dependency on joda-time. Consider adding it as an explicit dependency (so that Maven automatically includes it whenever httpdlog-parser is used), or better yet - drop the dependency entirely and migrate to the java.time implementation provided by Java 8 (which is very close to joda-time and is always available).

**Comment by nielsbasjes** [comment]
Thanks for pointing this out. 
For now I added it to the documentation that joda-time is needed also.
Initially it was part of the build and I took it out to get rid of nasty conflicts with  the joda-time that is included in pig. That is also the reason I'm using version 1.6 as the 'provided' version.
Currently the switch to Java 8 is not an option yet because much of the systems I use are using Java 7.
