### ISSUE TITLE
Add Jetty NCSARequestLog Parser

### ISSUE THREAD

**Issue by dynastywind** [nielsbasjes/logparser#30]
Hi, I'm using this great tool in my work to parse logs. It seems that current parsers can't parse Jetty's NCSA Request Log.
For example:
```
"%{User-Agent}i" %D
```
will fail to parse a record when user agent is null ("-" in the log), where there'll be one blank appended after "-". Thus the record will be
```
"-"  %D
```
Note there're two blanks between "-" and %D. Same problem also occurs for %h and %l when their values are "-".

Maybe it's necessary to add parser to parse NCSA Request Log and make this tool more powerful.

**Comment by nielsbasjes** [comment]
Can you send me a handful of loglines that show this effect?

**Comment by nielsbasjes** [comment]
So if I understand your description correctly if there is a value you see "value" yet when there is a null you see the "-" with an _extra_ space after it? If I understand correctly then this should first of all be a fix in Jetty (did you report this to them yet?). Like I said: It would really help if you could provide a few examples with both the correct value and with incorrect values. Thanks.

**Comment by nielsbasjes** [comment]
I downloaded the sources of Jetty and found the bug regarding the useragent string. 
I have not been able to find the other two. I applied a small fix in my parser (numerical values that can apparently be a '-' also) and described in the README.md how to workaround this Jetty problem.
Effectively this is done by using the fact you can specify multiple formats and the logparser automatically switches if a mismatch in the pattern is found... i.e. multiple parsers.

 Can you please verify this solution? 
Thanks.

**Comment by dynastywind** [comment]
Thank you for your response.
Here is a concrete example (some data has been modified).
```
192.168.1.1 -  -  [01/Jul/2016:07:23:27 +0000] "GET /example/show HTTP/1.1" 200 736 "-" "-"  417
```
which matches this pattern:
```
%h %l %u %{timestamp}i "%r" %>s %b "%L" "%{user-agent}i" %D
```
However, since **%l**, **%u** and **%{user-agent}i** are all null, they each are logged as:
```
- 
- 
"-" 
```
respectively. Notice that there's an extra space appended after those values. In the contrary, there will be no space if they're not null.

I've added a JettyNCSARequestLogParser in my own project by extending your parser, which is almost copy/paste work except for some small modifications since I can't find a better way to make a new parser based on your existing one. The most tricky part here is to parse
```
"-" 
```
since you firstly split on space and then do a match. Hence, we added a dummy space token parser to parse a space character to avoid this then we may no longer need to provide a second pattern string as you suggested in README doc.

I really hope if the existing parsers can be made more easier to be extended so that we can add some own patterns into those to parse some corner cases. Thank you very much.

**Comment by nielsbasjes** [comment]
First of all I see we agree that this behavior is a bug in this Jetty logging component.
Now let's see what this parser can provide without any changes, I think a lot.

I got the latest source from Jetty and I was unable to find the reason for the extra space with the %l and %u in the code base. I traced the history of the logging source file and this bug has been fixed in Jetty 9.2.5 that was released in november 2014 (see https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00070.html "449175 Removed extra space in NCSA log" ).

I checked the diff ( https://github.com/eclipse/jetty.project/commit/2332b4f ) and they actually logged " - " as the user if it was empty, now they log "-".
The %l entry is hardcoded to always be logged as "-", so no problem there, it is all in the %u value.

I double checked what my parser does in this exact scenario.

I initialized the parser with two formats with just space after the agent being different:

    %h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i" %D
    %h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i"  %D

When I parse the line you sent me this way I actually get " - " for the STRING:connection.client.user. So this is actually completely right from the perspective of the specified format.

I'll have a look if it is easily possible to include a clean workaround in the system.

**Comment by nielsbasjes** [comment]
Can you please test this: https://github.com/nielsbasjes/logparser/blob/master/README.md#parsing-problems-with-jetty-generated-logfiles

**Comment by dynastywind** [comment]
Hi, thank you for your update. I've tested by my own and it really works now.
Could you please update it on Maven with a version maybe 2.6-SNAPSHOT so that I can use it easier? And I'm really looking forward to your next release with these problems fixed, and maybe an easier extending architecture.
Thank you very much again.

**Comment by nielsbasjes** [comment]
Just now I pushed 2.6-SNAPSHOT to maven central
