### ISSUE TITLE
ApacheHttpdLoglineParser thread safety

### ISSUE THREAD

**Issue by java8964** [nielsbasjes/logparser#39]
Hi, 

I am interested in using your library in our Spark deployment. For simple testing, the parser works great for our Apache logs. 

One question I have is that the thread safety. I can see your library is using in the Hadoop/Hive/Pig, which normally parse the records in sequence in JVM processing. I wonder do you know that the "ApacheHttpdLoglineParser" parsing method is thread safe or not? In Spark, it indeed will run the parsing logic in multi-thread way, which could cause some issues for MR based code logic.

Thanks

**Comment by nielsbasjes** [comment]
Hi,

Great to hear you like it.
First of all please use HttpdLoglineParser class instead (the class you mentioned is there just for backwards compatibility. See https://github.com/nielsbasjes/logparser/blob/master/httpdlog/httpdlog-parser/src/main/java/nl/basjes/parse/httpdlog/ApacheHttpdLoglineParser.java#L22 ).

Now the parser was not written with Hadoop/Hive/Pig in mind to start with. 
I wrote it 'just a java library' that can be used in any jvm based project.

Now even if the code I have written is threadsafe (which I do not expect it to be), it would still be unwise to use it in such a way. The reason is that because it is dynamically pluggable (i.e. you can load extra dissectors) and making the threadsafe assumption would require all possible additions to be threadsafe too.

So I would simply go with "Not Threadsafe".
Simply creating a new instance for each thread should work fine.

Is this what you needed to know?

Niels Basjes

**Comment by java8964** [comment]
I will switch to use "HttpdLoglineParser".

No problem about threadsafe. I will create the parser instance per thread, and assume it is not threadsafe in general.

We have several cases won't be handled easy in our internal REGX implementation, but work out of box in your library. We will test the performance in our next step.

Thanks for such open source library.

**Comment by nielsbasjes** [comment]
You're welcome.

Please keep in mind while testing the performance that the actual 'runtime' parser depends on the fields you  actually ask for.

If (for example) you do not ask for any information from the URL then the parser will simply skip that entire part of the logline in the first parsing step. Also if you add an additional dissector (like [Yauaa](https://github.com/nielsbasjes/yauaa/blob/master/README-LogParser.md)) then the performance will be slower.

Just so you know.
