### ISSUE TITLE
cannot parse Nginx token : $upstream_response_time

### ISSUE THREAD

**Issue by beyond0573** [nielsbasjes/logparser#52]
hi,  in my project, i need to parse nginx log token $upstream_response_time, however i cannot find this token in NginxHttpdLogFormatDissector.java file

**Comment by nielsbasjes** [comment]
Can you please provide me with an example  of the full LogFormat and a handful of logged lines I can use as a test?

**Comment by jm-plagnard** [comment]
Never-mind, I realized that it was accessible through the following auto-generated field:

`"UNKNOWN_NGINX_VARIABLE:nginx.unknown.upstream_response_time" = "0.007"`

Thank you, it's a great library for parsing NGINX logs!

**Comment by nielsbasjes** [comment]
I'm currently working on this. I found a lot more fields in Nginx that are not yet supported.

Note that many of the fields in the upstream module are very nasty as in that they are a list of values with an optional redirect value. 
So instead of the basic 

> 0.001 

You can also have something like this (if I understand the documentation correctly) 

> 0.001 , 0.001 : 0.001 ,  0.001

**Comment by nielsbasjes** [comment]
Hi @beyond0573 , @jm-plagnard .
I pushed what I implemented the last few days.
Can you please check if I made any mistakes?
Thanks.

**Comment by beyond0573** [comment]
> Hi @beyond0573 , @jm-plagnard .
> I pushed what I implemented the last few days.
> Can you please check if I made any mistakes?
> Thanks.

can you release 5.2-snapshot version to maven repository ? currently I don't know how to use 5.2 version

**Comment by nielsbasjes** [comment]
Sure.
I just released 5.2-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots/

**Comment by beyond0573** [comment]
> Sure.
> I just released 5.2-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots/

thank you so much, this version helps me solve parse uptream time, appreciate your time!

**Comment by jm-plagnard** [comment]
Just tried, thanks for the release.
I see this now showing in the list of fields:
`
"UPSTREAM_SECOND_MILLIS_LIST:nginxmodule.upstream.response.time",
"SECOND_MILLIS:nginxmodule.upstream.response.time.0.value",
"MILLISECONDS:nginxmodule.upstream.response.time.0.value",
"MICROSECONDS:nginxmodule.upstream.response.time.0.value",
"SECOND_MILLIS:nginxmodule.upstream.response.time.0.redirected",
"MILLISECONDS:nginxmodule.upstream.response.time.0.redirected",
"MICROSECONDS:nginxmodule.upstream.response.time.0.redirected",
"SECOND_MILLIS:nginxmodule.upstream.response.time.1.value",
"MILLISECONDS:nginxmodule.upstream.response.time.1.value",
"MICROSECONDS:nginxmodule.upstream.response.time.1.value",
"SECOND_MILLIS:nginxmodule.upstream.response.time.1.redirected",
"MILLISECONDS:nginxmodule.upstream.response.time.1.redirected",
"MICROSECONDS:nginxmodule.upstream.response.time.1.redirected",
"SECOND_MILLIS:nginxmodule.upstream.response.time.2.value",
"MILLISECONDS:nginxmodule.upstream.response.time.2.value",
"MICROSECONDS:nginxmodule.upstream.response.time.2.value",

`
It goes up to 31 values

the UPSTREAM_SECOND_MILLIS_LIST:nginxmodule.upstream.response.time contains the expected value.
I'm just wondering what are the other ones.

**Comment by nielsbasjes** [comment]
@jm-plagnard Yes, that is what is supposed to happen.

If you read the documentation http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables
You can see that the upstream_response_time is (among others) a LIST of values with sometimes a value 'after redirecting'. 

I chose (because I do not have any better information) to limit the list to the first 32 entries. If this is wrong please tell me what is 'right'

So in fact your statement is wrong; the UPSTREAM_SECOND_MILLIS_LIST:nginxmodule.upstream.response.time you mentioned does NOT contain what you are looking for. The UPSTREAM_SECOND_MILLIS_LIST is a LIST of values and in your case this happens to be a list of 1 entry.

You probably want one of these because your list only has a single entry:

"SECOND_MILLIS:nginxmodule.upstream.response.time.0.value",
"MILLISECONDS:nginxmodule.upstream.response.time.0.value",
"MICROSECONDS:nginxmodule.upstream.response.time.0.value",

So please be careful with your logformat. Because this is a list you can easily create unparsable logfiles if you do not have enough separating markers between these lists.

I'm closing this issue as Fixed.

**Comment by jm-plagnard** [comment]
Thanks for the clarification, indeed my list contains only one value but could be multiples according to the NGINX documentation. I will use "SECOND_MILLIS:nginxmodule.upstream.response.time.0.value" in my case to be safe.
👍

**Comment by nielsbasjes** [comment]
I released version 5.2
