### ISSUE TITLE
[QUESTION]: Extra Fields in Results

### ISSUE THREAD

**Issue by cgivre** [nielsbasjes/logparser#57]
This is more of a question than an issue, but many of the fields have several versions of the same information.  For instance the useragent field may have a `first`, `original`, `last` version.  So my questions:
1.  What are these extra fields?
2.  It seems in all the data I've seen, these fields all have the same values.  Are they necessary and can they be disabled?

**Comment by nielsbasjes** [comment]
**1. What are these fields?**
In the access logs of the Apache httpd webserver some fields depend on where in the pipeline they are recorded. Because the system has a lot of rules and essentially scripting/proxying/redirecting/... built in: some things can change during the request.

For example https://httpd.apache.org/docs/current/mod/mod_log_config.html states for the `%s`

> %s | Status. For requests that have been internally redirected, this is 
> the status of the original request. Use %>s for the final status.

And more explicitly things can be modified in the format specification:

> The modifiers "<" and ">" can be used for requests that have been 
> internally redirected to choose whether the original or final (respectively) 
> request should be consulted. 
> By default, the % directives %s, %U, %T, %D, and %r look at the original request 
> while all others look at the final request. 
> So for example, %>s can be used to record the final status of the request 
> and %<u can be used to record the original authenticated user on a request 
> that is internally redirected to an unauthenticated resource.

**2. Can they be disabled?**
If you ask the logparser for 'all possible' fields it will give you all options it CAN extract, including all of those you saw.
The internal structure of the parser at runtime is optimized to only extract what you explicitly asked for.

So to disable them at runtime ... simply do not ask for them.

If you look at the [UDF for Apache Pig](https://github.com/nielsbasjes/logparser/blob/master/httpdlog/httpdlog-pigloader/src/main/java/nl/basjes/pig/input/apachehttpdlog/Loader.java#L447) you'll see that if you specify the parser to extract 10 fields, yet in your Pig script you only use 5 of them, then the actual runtime parser will only extract the 5 you selected.

Same mechanism.

**Comment by nielsbasjes** [comment]
@cgivre I assume you questions were answered. If not then please reopen this.
